name = "QEDFeynman"
uuid = "e5b388bf-6b77-4673-a798-c68c587e2b22"
authors = ["AntonReinhard <anton.reinhard@proton.me>"]
version = "0.1.0"

[deps]
AccurateArithmetic = "22286c92-06ac-501d-9306-4abd417d9753"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GraphComputing = "62933717-1c9d-4a3f-b06f-7ab7f17ca32d"
QEDbase = "10e22c08-3ccb-4172-bfcf-7d7aa3d04d93"
QEDcore = "35dc0263-cb5f-4c33-a114-1d7f54ab753e"
QEDprocesses = "46de9c38-1bb3-4547-a1ec-da24d767fdad"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TypeUtils = "c3b1956e-8857-4d84-9b79-890df85b1e67"

[extras]
GraphComputing = "62933717-1c9d-4a3f-b06f-7ab7f17ca32d"
QEDbase = "10e22c08-3ccb-4172-bfcf-7d7aa3d04d93"
QEDcore = "35dc0263-cb5f-4c33-a114-1d7f54ab753e"
QEDprocesses = "46de9c38-1bb3-4547-a1ec-da24d767fdad"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SafeTestsets", "Test", "GraphComputing", "QEDbase", "QEDcore", "QEDprocesses"]
